In [1]:
## ANN keras

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

## data preprocessing

dataset = pd.read_csv('Churn_Modelling.csv')

dataset.head()

x = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

## matrix of x and y are created
x
y

## split the data into training and test

## before splitting the data we must encode categorical variables

from sklearn.preprocessing import LabelEncoder, OneHotEncoder
label_encoder_x_1 = LabelEncoder()
x[:,1] = label_encoder_x_1.fit_transform(x[:,1])

label_encoder_x_2 = LabelEncoder()
x[:,2] = label_encoder_x_2.fit_transform(x[:,2])

x

## create dummy variable
oneHotEncoder = OneHotEncoder(categorical_features=[1])
x = oneHotEncoder.fit_transform(x).toarray()

x.shape

x1 = pd.DataFrame(x)

x1.head()
## remove one dummy variable to remove the dummy variable trap

## column 0 will be removed
x1.drop(0, axis =1, inplace = True)

x1.head()

x1.shape

## now split the data into tst and train set

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x1, y, test_size=0.2, random_state=42)

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

X_tarin = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

import keras

## Part 3

from keras.models import Sequential
from keras.layers import Dense

## define the sequence of layers
classifier = Sequential()



X_tarin.shape

## add the input layer and first hidden layer
classifier.add(Dense(output_dim = 6, init = 'uniform', activation= 'relu', input_dim = 11 ))


## second hidden layer
classifier.add(Dense(output_dim = 6, init = 'uniform', activation= 'relu'))



classifier.add(Dense(output_dim = 1, init = 'uniform', activation= 'sigmoid'))
## for more that 2 op we use softmax function



## compiling ANN

classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])



classifier.fit(X_tarin, y_train, batch_size= 10, epochs= 100)

In [149]:
## now test it on test set

In [150]:
y_pred = classifier.predict(X_test)

In [151]:
y_pred

array([[0.13718857],
       [0.10958184],
       [0.39742905],
       ...,
       [0.46635193],
       [0.0470388 ],
       [0.21383433]], dtype=float32)

In [152]:
y_test

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

In [153]:
type(y_pred)

numpy.ndarray

In [154]:
type(y_test)

numpy.ndarray

In [157]:
## compare both y_pred and y_test, with help of confusion matrix
## we must decide when predicted result is 1 and when 0 , by applying a threshold

In [158]:
y_pred = (y_pred> 0.5)

In [159]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [160]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [161]:
cm

array([[1550,   57],
       [ 256,  137]], dtype=int64)

In [162]:
## confirm it with acuraccy

In [163]:
(1550 + 137)/ (1550+137+57+256)

0.8435

# Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France
Credit Score: 600
Gender: Male
Age: 40 years old
Tenure: 3 years
Balance: $60000
Number of Products: 2
Does this customer have a credit card ? Yes
Is this customer an Active Member: Yes
Estimated Salary: $50000
So should we say goodbye to that customer ?

The solution is provided in the next Lecture but I strongly recommend that you try to solve it on your own.

In [164]:
## put these informations in a horizontal manner

In [172]:
## male = 1
## france = 0,0
Homework_predictions = classifier.predict(sc.transform(np.array([[0,0,600,1,40, 3 , 60000, 2, 1, 1, 50000 ]])))

## now we need to do feature scalling


C:\Users\INTEL\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int32 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [168]:
dataset.head(10)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   
5          6    15574012       Chu          645     Spain    Male   44   
6          7    15592531  Bartlett          822    France    Male   50   
7          8    15656148    Obinna          376   Germany  Female   29   
8          9    15792365        He          501    France    Male   44   
9         10    15592389        H?          684    France    Male   27   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   
5       8  113755.78              2          1               0   
6       7       0.00              2          1               1   
7       4  115046.74              4          1               0   
8       4  142051.07              2          0               1   
9       2  134603.88              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0  
5        149756.71       1  
6         10062.80       0  
7        119346.88       1  
8         74940.50       0  
9         71725.73       0

In [169]:
x1.head(10)

1    2      3    4     5    6          7    8    9    10         11
0  0.0  0.0  619.0  0.0  42.0  2.0       0.00  1.0  1.0  1.0  101348.88
1  0.0  1.0  608.0  0.0  41.0  1.0   83807.86  1.0  0.0  1.0  112542.58
2  0.0  0.0  502.0  0.0  42.0  8.0  159660.80  3.0  1.0  0.0  113931.57
3  0.0  0.0  699.0  0.0  39.0  1.0       0.00  2.0  0.0  0.0   93826.63
4  0.0  1.0  850.0  0.0  43.0  2.0  125510.82  1.0  1.0  1.0   79084.10
5  0.0  1.0  645.0  1.0  44.0  8.0  113755.78  2.0  1.0  0.0  149756.71
6  0.0  0.0  822.0  1.0  50.0  7.0       0.00  2.0  1.0  1.0   10062.80
7  1.0  0.0  376.0  0.0  29.0  4.0  115046.74  4.0  1.0  0.0  119346.88
8  0.0  0.0  501.0  1.0  44.0  4.0  142051.07  2.0  0.0  1.0   74940.50
9  0.0  0.0  684.0  1.0  27.0  2.0  134603.88  1.0  1.0  1.0   71725.73

In [174]:
Homework_predictions = (Homework_predictions>0.5)

In [175]:
Homework_predictions

array([[False]])

In [176]:
## False the custmer doesnot leave the bank

###############################################################################
##Evaluating ANN